server:
  port: 9106
eureka:
  client:
    service-url:
      # 注册到集群，就把多个Eurekaserver地址使用逗号连接起来即可；注册到单实例（非集群模式），那就写一个就ok
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
  instance:
    prefer-ip-address: true  #服务实例中显示ip，而不是显示主机名（兼容老的eureka版本）
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
    name: minyue-spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/minyue-chd/spring-cloud-config.git
          username: minyue-chd #配置git用户名
          password: xiaoku5752170 #配置git密码
          search-paths:
            - spring-cloud-config
      # 读取分支
      label: master
  rabbitmq:
    host: 81.71.123.45
    port: 87
    username: guest
    password: guest
#针对的被调用方微服务名称,不加就是全局生效
#lagou-service-resume:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #负载策略调整
# springboot中暴露健康检查等断点接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # 暴露健康接口的细节
  endpoint:
    health:
      show-details: always

